#!/bin/bash

echo "================================================================================"
echo "Cleaning Journal"
journalctl --vacuum-size=20M

echo "Cleaning Docker"
echo y | docker system prune
echo "================================================================================"
