"""users table

Revision ID: 414c3d6039dd
Revises: 
Create Date: 2020-11-04 21:37:56.103858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414c3d6039dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_user_username'), 'planner_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planner_user_username'), table_name='planner_user')
    op.drop_table('planner_user')
    # ### end Alembic commands ###
